""" Constants file for AIC's seed project
"""
AIC_CLIENT_ID = 'AIC_CLIENT_ID'
AIC_CLIENT_SECRET = 'AIC_CLIENT_SECRET'
AIC_CUSTOMER_ID = 'AIC_CUSTOMER_ID'
AIC_CALLBACK_URL = 'AIC_CALLBACK_URL'
AIC_DOMAIN = 'AIC_DOMAIN'
AIC_AUDIENCE = 'AIC_AUDIENCE'
PROFILE_KEY = 'profile'
SECRET_KEY = 'ThisIsTheSecretKey'
JWT_PAYLOAD = 'jwt_payload'